### PR TITLE
Adds an inversion-of-control container to support further refactoring

### PR DESCRIPTION
**Pull request by mslipper**
Also fixes bug in NEDB channels database

### CODE REVIEW

**Comment by ukstv** [comment]
Do I understand correctly, that works globally across all the instances of machinomy object?

**Comment by mslipper** [comment]
Correct. My understanding is that the Machinomy object itself will be instantiated once.

**Comment by ukstv** [comment]
I imagine the case of multiple instances is not so far fetched. Moreover, I would see a scenario which employs different instances of smart contract on a private network, other than provided by @machinomy/contracts. Could you adjust the code for that, please?

**Comment by mslipper** [comment]
Works for me. Will have an update shortly.

**Comment by mslipper** [comment]
Done. New instances of Machinomy will receive fresh instances of all resolved services. We'll need additional refactoring work (beyond just adding the IOC container) to support non-`@machinomy` smart contracts, but that's at least possible now.

**Comment by ukstv** [comment]
Cool!

**Pull request merged**
