### PR TITLE
Store deposit results in DB

### PR DESCRIPTION
**Pull request by mslipper**

### CODE REVIEW

**Comment by xJeneKx** [comment]
Why are you using the database instead of the contract?

**Comment by mslipper** [comment]
That method didn't exist when I opened this PR.

**Comment by ukstv** [comment]
What would change if we have channel value read from the contract, as per #169 ?

**Comment by ukstv** [comment]
Closed by mistake. Reopened.

**Comment by mslipper** [comment]
I can make this change. My only worries are consistency between the database and the contract and scalability since if there are a lot of channels then we'll be making a lot of RPC requests to the geth node.

**Comment by ukstv** [comment]
Geth node is local anyway. We localise then a possible inconsistency.

**Comment by mslipper** [comment]
Ok. I'll have to move the code in channel_manager to the dao otherwise there will be a circular dependency.

**Comment by mslipper** [comment]
Done.

**Pull request merged**
